title = "Ananke"
baseURL = "https://gohugo-ananke-theme-demo.netlify.com/"
languageCode = "fr"
theme = "gohugo-theme-ananke"


MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "The last theme you'll ever need. Maybe."
  faceboook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"

[languages]
  [languages.fr]
    title = "ZE LANGUE EST DE RETOURNÉE"
  [[Languages.fr.menu.languages]]
     name = "English"
     identifier = ""
     weight = 5
     url = "/en"

  [languages.en]
    title = "ZE LANGUAGE HAZ RETURN'D!"
  [[Languages.en.menu.languages]]
     name = "Français"
     identifier = ""
     weight = 5
     url = "/fr"


